"""
Emit SQL to seed hydrus.mime from hydrus's own constants.

The mime table is the one lookup that is a table rather than a PG enum, because
hydrus adds mimes most releases. Generating it from HydrusConstants rather than
hand-maintaining a copy means it cannot drift -- rerun this after a hydrus
update and apply the output.

    python postgres_sync/seed_mimes.py | psql "$HYDRUS_PG_CONNECTION"

Run from the hydrus repo root.
"""

import os
import sys

sys.path.insert( 0, os.path.join( os.path.dirname( os.path.abspath( __file__ ) ), '..' ) )

from hydrus.core import HydrusConstants as HC


# HC.GENERAL_* -> our filetype enum labels
GENERAL_TO_FILETYPE = {
    HC.GENERAL_IMAGE                : 'image',
    HC.GENERAL_ANIMATION            : 'animation',
    HC.GENERAL_VIDEO                : 'video',
    HC.GENERAL_AUDIO                : 'audio',
    HC.GENERAL_APPLICATION_ARCHIVE  : 'archive',
    HC.GENERAL_IMAGE_PROJECT        : 'image_project',
    HC.GENERAL_APPLICATION          : 'application'
}


def sql_str( s ):

    return "'" + s.replace( "'", "''" ) + "'"


def main():

    rows = []

    for ( mime, code ) in sorted( HC.mime_string_lookup.items() ):

        # Undetermined placeholders are hydrus-internal ambiguity markers, not
        # real filetypes -- a file never lands in the db with one.
        if mime in ( HC.UNDETERMINED_WM, HC.UNDETERMINED_MP4, HC.UNDETERMINED_PNG ):

            continue


        general = HC.mimes_to_general_mimetypes.get( mime )

        filetype = GENERAL_TO_FILETYPE.get( general )

        if filetype is None:

            # No general grouping upstream -- treat as a plain application blob
            # rather than dropping the row, so file.mime never dangles.
            filetype = 'application'


        media_type = HC.mime_mimetype_string_lookup.get( mime, 'application/octet-stream' )

        ext = HC.mime_ext_lookup.get( mime, '' )

        searchable = mime in HC.SEARCHABLE_MIMES

        rows.append( ( code, media_type, ext, filetype, mime, searchable ) )


    print( '-- generated by postgres_sync/seed_mimes.py from hydrus {}'.format( HC.SOFTWARE_VERSION ) )
    print( 'BEGIN;' )

    for ( code, media_type, ext, filetype, hydrus_enum, searchable ) in rows:

        print(
            'INSERT INTO hydrus.mime (code, media_type, extension, filetype, hydrus_enum, searchable) '
            'VALUES ({}, {}, {}, {}, {}, {}) '
            'ON CONFLICT (code) DO UPDATE SET media_type = EXCLUDED.media_type, '
            'extension = EXCLUDED.extension, '
            'filetype = EXCLUDED.filetype, hydrus_enum = EXCLUDED.hydrus_enum, '
            'searchable = EXCLUDED.searchable;'.format(
                sql_str( code ),
                sql_str( media_type ),
                sql_str( ext ),
                sql_str( filetype ) + '::hydrus.filetype',
                hydrus_enum,
                'true' if searchable else 'false'
            )
        )


    print( 'COMMIT;' )
    print( '-- {} mimes'.format( len( rows ) ) )


if __name__ == '__main__':

    main()
