// <auto-generated />
using System;
using HydrusReadModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HydrusReadModel.Migrations
{
    [DbContext(typeof(HydrusDbContext))]
    partial class HydrusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hydrus")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hydrus", "content_status", new[] { "current", "deleted", "pending", "petitioned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hydrus", "discrepancy_kind", new[] { "extra", "mismatch", "missing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hydrus", "filetype", new[] { "animation", "application", "archive", "audio", "image", "image_project", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hydrus", "service_type", new[] { "client_api_service", "combined_deleted_file", "combined_file", "combined_local_file_domains", "combined_tag", "file_repository", "hydrus_local_file_storage", "ipfs", "local_booru", "local_file_domain", "local_file_trash_domain", "local_file_update_domain", "local_notes", "local_rating_incdec", "local_rating_like", "local_rating_numerical", "local_tag", "message_depot", "null_service", "rating_like_repository", "rating_numerical_repository", "server_admin", "tag_repository", "test_service" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hydrus", "sync_kind", new[] { "backfill", "drain", "reconcile" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HydrusReadModel.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("FileId"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<bool?>("HasAudio")
                        .HasColumnType("boolean")
                        .HasColumnName("has_audio");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeCode")
                        .HasColumnType("text")
                        .HasColumnName("mime_code");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long?>("NumFrames")
                        .HasColumnType("bigint")
                        .HasColumnName("num_frames");

                    b.Property<long?>("NumWords")
                        .HasColumnType("bigint")
                        .HasColumnName("num_words");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("FileId")
                        .HasName("pk_file");

                    b.HasIndex("MimeCode")
                        .HasDatabaseName("ix_file_mime_code");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_file_sha256");

                    b.ToTable("file", "hydrus", t =>
                        {
                            t.HasCheckConstraint("ck_file_sha256_length", "octet_length(sha256) = 32");
                        });
                });

            modelBuilder.Entity("HydrusReadModel.FileNote", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("FileId", "Name")
                        .HasName("pk_file_note");

                    b.HasIndex("Body")
                        .HasDatabaseName("ix_file_note_body_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Body"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Body"), new[] { "gin_trgm_ops" });

                    b.ToTable("file_note", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.FileOtherHash", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<byte[]>("Md5")
                        .HasColumnType("bytea")
                        .HasColumnName("md5");

                    b.Property<byte[]>("Sha1")
                        .HasColumnType("bytea")
                        .HasColumnName("sha1");

                    b.Property<byte[]>("Sha512")
                        .HasColumnType("bytea")
                        .HasColumnName("sha512");

                    b.HasKey("FileId")
                        .HasName("pk_file_other_hash");

                    b.HasIndex("Md5")
                        .HasDatabaseName("ix_file_other_hash_md5")
                        .HasFilter("md5 IS NOT NULL");

                    b.HasIndex("Sha1")
                        .HasDatabaseName("ix_file_other_hash_sha1")
                        .HasFilter("sha1 IS NOT NULL");

                    b.ToTable("file_other_hash", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.FilePhash", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<int>("PhashId")
                        .HasColumnType("integer")
                        .HasColumnName("phash_id");

                    b.HasKey("FileId", "PhashId")
                        .HasName("pk_file_phash");

                    b.HasIndex("PhashId", "FileId")
                        .HasDatabaseName("ix_file_phash_phash_id_file_id");

                    b.ToTable("file_phash", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.FileServiceStatus", b =>
                {
                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.Property<ContentStatus>("Status")
                        .HasColumnType("hydrus.content_status")
                        .HasColumnName("status");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<DateTimeOffset?>("OriginalImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_imported_at");

                    b.HasKey("ServiceId", "Status", "FileId")
                        .HasName("pk_file_service_status");

                    b.HasIndex("FileId", "ServiceId")
                        .HasDatabaseName("ix_file_service_status_file_id_service_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("FileId", "ServiceId"), new[] { "Status" });

                    b.HasIndex("ServiceId", "ImportedAt", "FileId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_file_service_status_current")
                        .HasFilter("status = 'current'");

                    b.ToTable("file_service_status", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.FileTag", b =>
                {
                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.Property<ContentStatus>("Status")
                        .HasColumnType("hydrus.content_status")
                        .HasColumnName("status");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.HasKey("ServiceId", "Status", "TagId", "FileId")
                        .HasName("pk_file_tag");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_tag_file_id");

                    b.HasIndex("ServiceId", "Status", "FileId", "TagId")
                        .HasDatabaseName("ix_file_tag_service_id_status_file_id_tag_id");

                    b.ToTable("file_tag", "hydrus");

                    b.HasAnnotation("Npgsql:StorageParameter:fillfactor", 100);
                });

            modelBuilder.Entity("HydrusReadModel.FileUrl", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer")
                        .HasColumnName("url_id");

                    b.HasKey("FileId", "UrlId")
                        .HasName("pk_file_url");

                    b.HasIndex("UrlId", "FileId")
                        .HasDatabaseName("ix_file_url_url_id_file_id");

                    b.ToTable("file_url", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.Mime", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<Filetype>("Filetype")
                        .HasColumnType("hydrus.filetype")
                        .HasColumnName("filetype");

                    b.Property<short>("HydrusEnum")
                        .HasColumnType("smallint")
                        .HasColumnName("hydrus_enum");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<bool>("Searchable")
                        .HasColumnType("boolean")
                        .HasColumnName("searchable");

                    b.HasKey("Code")
                        .HasName("pk_mime");

                    b.HasIndex("Extension")
                        .HasDatabaseName("ix_mime_extension");

                    b.HasIndex("Filetype")
                        .HasDatabaseName("ix_mime_filetype");

                    b.HasIndex("HydrusEnum")
                        .IsUnique()
                        .HasDatabaseName("ix_mime_hydrus_enum");

                    b.HasIndex("MediaType")
                        .HasDatabaseName("ix_mime_media_type");

                    b.ToTable("mime", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.Phash", b =>
                {
                    b.Property<int>("PhashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("phash_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PhashId"));

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phash");

                    b.HasKey("PhashId")
                        .HasName("pk_phash");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_phash_phash");

                    b.ToTable("phash", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.Service", b =>
                {
                    b.Property<short>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("ServiceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("ServiceKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("service_key");

                    b.Property<ServiceType>("ServiceType")
                        .HasColumnType("hydrus.service_type")
                        .HasColumnName("service_type");

                    b.HasKey("ServiceId")
                        .HasName("pk_service");

                    b.HasIndex("ServiceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_service_service_key");

                    b.HasIndex("ServiceType")
                        .HasDatabaseName("ix_service_service_type");

                    b.ToTable("service", "hydrus", t =>
                        {
                            t.HasCheckConstraint("ck_service_key_length", "octet_length(service_key) = 32");
                        });
                });

            modelBuilder.Entity("HydrusReadModel.SyncDiscrepancy", b =>
                {
                    b.Property<long>("DiscrepancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("discrepancy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DiscrepancyId"));

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("FoundAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("found_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DiscrepancyKind>("Kind")
                        .HasColumnType("hydrus.discrepancy_kind")
                        .HasColumnName("kind");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.HasKey("DiscrepancyId")
                        .HasName("pk_sync_discrepancy");

                    b.ToTable("sync_discrepancy", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.SyncRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RunId"));

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<SyncKind>("Kind")
                        .HasColumnType("hydrus.sync_kind")
                        .HasColumnName("kind");

                    b.Property<bool?>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<long>("RowsApplied")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_applied");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RunId")
                        .HasName("pk_sync_run");

                    b.ToTable("sync_run", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.SyncState", b =>
                {
                    b.Property<string>("Stream")
                        .HasColumnType("text")
                        .HasColumnName("stream");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seq");

                    b.Property<byte[]>("SourceDbId")
                        .HasColumnType("bytea")
                        .HasColumnName("source_db_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Stream")
                        .HasName("pk_sync_state");

                    b.ToTable("sync_state", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("TagId"));

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("namespace");

                    b.Property<string>("Subtag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtag");

                    b.Property<string>("TagText")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("tag")
                        .HasComputedColumnSql("CASE WHEN namespace = '' THEN subtag ELSE namespace || ':' || subtag END", true);

                    b.HasKey("TagId")
                        .HasName("pk_tag");

                    b.HasIndex("Namespace")
                        .HasDatabaseName("ix_tag_namespace")
                        .HasFilter("namespace <> ''");

                    b.HasIndex("Subtag")
                        .HasDatabaseName("ix_tag_subtag_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Subtag"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Subtag"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Namespace", "Subtag")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_namespace_subtag");

                    b.ToTable("tag", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.TagParent", b =>
                {
                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.Property<ContentStatus>("Status")
                        .HasColumnType("hydrus.content_status")
                        .HasColumnName("status");

                    b.Property<int>("ChildTagId")
                        .HasColumnType("integer")
                        .HasColumnName("child_tag_id");

                    b.Property<int>("ParentTagId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_tag_id");

                    b.HasKey("ServiceId", "Status", "ChildTagId", "ParentTagId")
                        .HasName("pk_tag_parent");

                    b.HasIndex("ServiceId", "Status", "ParentTagId", "ChildTagId")
                        .HasDatabaseName("ix_tag_parent_service_id_status_parent_tag_id_child_tag_id");

                    b.ToTable("tag_parent", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.TagSibling", b =>
                {
                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.Property<ContentStatus>("Status")
                        .HasColumnType("hydrus.content_status")
                        .HasColumnName("status");

                    b.Property<int>("BadTagId")
                        .HasColumnType("integer")
                        .HasColumnName("bad_tag_id");

                    b.Property<int>("GoodTagId")
                        .HasColumnType("integer")
                        .HasColumnName("good_tag_id");

                    b.HasKey("ServiceId", "Status", "BadTagId", "GoodTagId")
                        .HasName("pk_tag_sibling");

                    b.ToTable("tag_sibling", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.Url", b =>
                {
                    b.Property<int>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("url_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UrlId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.HasKey("UrlId")
                        .HasName("pk_url");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("ix_url_url");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_url_domain");

                    b.ToTable("url", "hydrus");
                });

            modelBuilder.Entity("HydrusReadModel.File", b =>
                {
                    b.HasOne("HydrusReadModel.Mime", "Mime")
                        .WithMany("Files")
                        .HasForeignKey("MimeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_mime_mime_code");

                    b.Navigation("Mime");
                });

            modelBuilder.Entity("HydrusReadModel.FileNote", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithMany("Notes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_note_file_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusReadModel.FileOtherHash", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithOne("OtherHashes")
                        .HasForeignKey("HydrusReadModel.FileOtherHash", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_other_hash_file_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("HydrusReadModel.FilePhash", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithMany("Phashes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_phash_file_file_id");

                    b.HasOne("HydrusReadModel.Phash", "Phash")
                        .WithMany()
                        .HasForeignKey("PhashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_phash_phash_phash_id");

                    b.Navigation("File");

                    b.Navigation("Phash");
                });

            modelBuilder.Entity("HydrusReadModel.FileServiceStatus", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithMany("ServiceStatuses")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_service_status_file_file_id");

                    b.HasOne("HydrusReadModel.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_service_status_service_service_id");

                    b.Navigation("File");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HydrusReadModel.FileTag", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithMany("Tags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_tag_file_file_id");

                    b.HasOne("HydrusReadModel.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_tag_service_service_id");

                    b.HasOne("HydrusReadModel.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_tag_tag_tag_id");

                    b.Navigation("File");

                    b.Navigation("Service");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HydrusReadModel.FileUrl", b =>
                {
                    b.HasOne("HydrusReadModel.File", "File")
                        .WithMany("Urls")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_url_file_file_id");

                    b.HasOne("HydrusReadModel.Url", "Url")
                        .WithMany()
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_url_url_url_id");

                    b.Navigation("File");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("HydrusReadModel.TagParent", b =>
                {
                    b.HasOne("HydrusReadModel.Tag", "ChildTag")
                        .WithMany()
                        .HasForeignKey("ChildTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_parent_tag_child_tag_id");

                    b.HasOne("HydrusReadModel.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_parent_tag_parent_tag_id");

                    b.HasOne("HydrusReadModel.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_parent_service_service_id");

                    b.Navigation("ChildTag");

                    b.Navigation("ParentTag");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HydrusReadModel.TagSibling", b =>
                {
                    b.HasOne("HydrusReadModel.Tag", "BadTag")
                        .WithMany()
                        .HasForeignKey("BadTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_sibling_tag_bad_tag_id");

                    b.HasOne("HydrusReadModel.Tag", "GoodTag")
                        .WithMany()
                        .HasForeignKey("GoodTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_sibling_tag_good_tag_id");

                    b.HasOne("HydrusReadModel.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_sibling_service_service_id");

                    b.Navigation("BadTag");

                    b.Navigation("GoodTag");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HydrusReadModel.File", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("OtherHashes");

                    b.Navigation("Phashes");

                    b.Navigation("ServiceStatuses");

                    b.Navigation("Tags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("HydrusReadModel.Mime", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
